name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cget
      run: pip install cget 
    - name: SDL2
      run: cget install sdl2
    - name: build
      run: bash ./build.sh
